### ISSUE TITLE
Resolve redesign

### ISSUE THREAD

**Issue by itsjohncs** [Khan/engblog#13]
I hit a dead end with the design I was using before, and couldn't figure out how to add in the pieces I wanted. So I scrapped it and am trying for a two-column responsive layout now.

There is no index page now, and the posts are instead available on the left nav bar, along with the subscription messaging. The nav bar will jump up onto the top of the page when the width gets small enough, and the info under the logo will be shown through a menu button.

![screen shot 2015-05-23 at 1 05 53 am](https://cloud.githubusercontent.com/assets/367832/7783054/514578bc-00e8-11e5-8047-34b654540747.png)

I'm not sure whether this will be a good road to go down but I've been having a much easier time working within this structure so I suspect this'll be the way to go.

**Comment by itsjohncs** [comment]
Some weak points right now:

### Subscription

The subscription messaging seems very subtle. Given that that's very important, it might be a good idea to make it a little louder. On the other hand, subscribing is something people will naturally think of if they like what they read in the post... So it might be distracting if we call attention to it before the user is ready to click it.

Alternatively (or just in addition to whatever else I do), I can add some callouts at the bottom of the post to catch users who liked the post, and wouldn't immediately think to look for a way to subscribe.

### Mysterious Colors

The team tags were a much bigger piece of the previous design, but they got smaller and smaller and now they're just a single little line next to the post.

Those lines are not explained, and they _do_ have meaning, so I suspect some people might be confused. They're serving the purpose of grouping the post title and metadata, as well as giving the side bar splashes of color, so it might be OK to just let it be, but I wish I could figure out a way to convey what team each post is coming from more clearly.

### People

I want more emphasis on the posters if possible, and I haven't really figured out how to do that... This might be enough though. A big badge is probably not really necessary.

**Comment by itsjohncs** [comment]
Got some feedback from my SO, going to try and put some more explicit emphasis on the subscribe buttons.

![screen shot 2015-05-23 at 2 47 59 pm](https://cloud.githubusercontent.com/assets/367832/7785860/c6599382-015a-11e5-9bff-944de70650bc.png)

I can also make the upcoming post clickable, and it brings you to a partial post page that potentially gives some additional teaser information, as well as a big ole' subscription call out. Because if the user wants to read the post, they'll have a solid internal reason to subscribe.

**Comment by itsjohncs** [comment]
Mobile version is coming along :).

![screen shot 2015-05-23 at 7 37 41 pm](https://cloud.githubusercontent.com/assets/367832/7786418/44376ae0-0183-11e5-9490-296486b32f67.png)

**Comment by k4b7** [comment]
Nice!

**Comment by itsjohncs** [comment]
:).

Haven't explicitly figured out what browsers I want to support yet, so to put a target on the board: I'll plan on trying to support IE 9 and above. Anything before that would be a real drag. I don't think I need to worry overmuch about the other browsers as far as supporting various features go, but I'll make sure to do cross browser testing.

**Comment by k4b7** [comment]
I wouldn't bother with IE 9 considering who the target audience is, but that's just me.

**Comment by itsjohncs** [comment]
IE 9 and above is pretty straightforward to support, which is why I picked that as that target. I agree that it's not really necessary though, I doubt IE 9 is going to be a big part of our market. A bunch of weird mobile browsers is probably something to worry about though.

Anyways, design is pretty much done, I put up [a request for feedback](https://app.asana.com/0/20971210297637/35538770431975) on the design asana queue though.
