### ISSUE TITLE
add "discuss this on HN" links

### ISSUE THREAD

**Issue by k4b7** [Khan/engblog#29]
I usually see this at the bottom articles.  Not sure if that's the best place for it.

**Comment by itsjohncs** [comment]
I think this issue might be a dupe of #12. I think the bottom is probably a good place for it. It's usually where comments go anyways and that's basically what this would be. Calling out that people can also tweet at @KAEngineering might also be a good idea.

**Comment by k4b7** [comment]
totally a dupe
